[package]
name = "v2v"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
"num-traits" = "0.2"
"num-rational" = { version = "0.4", features=["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
"dve-lib" = { path = "./dve-lib" }
clap = { version = "4.4.6", features = ["derive"] }
pretty_env_logger = "0.5.0"
log = "0.4.20"

[workspace]
members = [
    "dve-lib"
]
